#Ansible Playbook
-
  name: Deploy Web Application
  hosts: db_and_web_server1,db_and_web_server2
  become: true
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=installed force=yes
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essentials
        - python-pip
        - python-mysqldb    
    - include: tasks/deploy_db.yaml
    - include: tasks/deploy_web.yml
