#Ansible Tasks File tasks/deploy_web.yml
    - name: Install Python Flask Dependencies
      pip: 
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - flask_mysql 
    
    - name: Copy Source Code
      copy: src=app.py dest=/opt/app.py

    - name: Start Web Server
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &